apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ekt-ecard.fullname" . }}-ecard-app-postgres-pvc
  labels:
    app: {{ include "ekt-ecard.name" . }}-ecard-app-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ecardAppPostgres.storage }}
