apiVersion: v1
kind: Service
metadata:
  name: {{ include "ekt-ecard.fullname" . }}-ecard-app-redis
  labels:
    app: {{ include "ekt-ecard.name" . }}-ecard-app-redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: {{ .Values.ecardAppRedis.port }}
      targetPort: {{ .Values.ecardAppRedis.port }}
  selector:
    app: {{ include "ekt-ecard.name" . }}-ecard-app-redis
