apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prometheus.name }}
  labels:
    app: {{ .Values.prometheus.name }}
spec:
  replicas: {{ .Values.prometheus.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.prometheus.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.prometheus.name }}
    spec:
      containers:
        - name: {{ .Values.prometheus.name }}
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          ports:
            - containerPort: {{ .Values.prometheus.containerPort }}
              hostPort: {{ .Values.prometheus.hostPort }}
              protocol: TCP
          args:
            - --enable-feature=exemplar-storage
            - --config.file=/etc/prometheus/prometheus.yml
          volumeMounts:
            - mountPath: /etc/prometheus/prometheus.yml
              name: prometheus-config
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
