apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ekt-ecard.fullname" . }}-ecard-mongodb-pvc
  labels:
    app: {{ include "ekt-ecard.name" . }}-ecard-mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ecardMongodb.storage }}
