apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ecard-logstash
  labels:
    app: {{ .Release.Name }}-ecard-logstash
spec:
  ports:
    - name: logstash
      port: 5044
      targetPort: 5044
    - name: logstash-http
      port: 9600
      targetPort: 9600
  selector:
    app: {{ .Release.Name }}-ecard-logstash
