apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ekt-ecard.fullname" . }}-ecard-app-postgres
  labels:
    app: {{ include "ekt-ecard.name" . }}-ecard-app-postgres
spec:
  replicas: {{ .Values.ecardAppPostgres.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ekt-ecard.name" . }}-ecard-app-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ include "ekt-ecard.name" . }}-ecard-app-postgres
    spec:
      containers:
        - name: ecard-app-postgres
          image: "{{ .Values.ecardAppPostgres.image }}"
          env:
            - name: POSTGRES_DB
              value: {{ .Values.ecardAppPostgres.env.POSTGRES_DB }}
            - name: POSTGRES_USER
              value: {{ .Values.ecardAppPostgres.env.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.ecardAppPostgres.env.POSTGRES_PASSWORD }}
          ports:
            - containerPort: {{ .Values.ecardAppPostgres.port }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ include "ekt-ecard.fullname" . }}-ecard-app-postgres-pvc
