apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ekt-ecard.fullname" . }}-ecard-neo4j-pvc
  labels:
    app: {{ include "ekt-ecard.name" . }}-ecard-neo4j
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ecardNeo4j.storage }}
