apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ekt-ecard.fullname" . }}-ecard-chat-redis-pvc
  labels:
    app: {{ include "ekt-ecard.name" . }}-ecard-chat-redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ecardChatRedis.storage }}
