apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grafana.name }}
  labels:
    app: {{ .Values.grafana.name }}
spec:
  selector:
    app: {{ .Values.grafana.name }}
  ports:
    - name: http
      port: {{ .Values.grafana.servicePort }}
      targetPort: {{ .Values.grafana.containerPort }}
